[package]
name = "sample"
version = "0.1.0"
authors = ["keyolk"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.probe]
git = "https://github.com/cuviper/rust-libprobe.git"

[profile.release]
opt-level = 0
